### ISSUE TITLE
Add --meta-buildtime-dep

### ISSUE THREAD

**Issue by torsava** [sclorg/spec2scl#12]
Originally reported by: **Slavek Kabrda (Bitbucket: [bkabrda](https://bitbucket.org/bkabrda), GitHub: [bkabrda](https://github.com/bkabrda))**

----------------------------------------

${subject} as a counterpart of --meta-runtime-dep.

----------------------------------------
- Bitbucket: https://bitbucket.org/bkabrda/spec2scl/issue/12

**Comment by irushchyshyn** [comment]
%{scl}-runtime dependency is now added automatically for buildtime as part of #16.

Closing the issue. Please reopen if necessary.
