### ISSUE TITLE
Transformers should expect whitespace at line start

### ISSUE THREAD

**Issue by torsava** [sclorg/spec2scl#15]
Originally reported by: **Slavek Kabrda (Bitbucket: [bkabrda](https://bitbucket.org/bkabrda), GitHub: [bkabrda](https://github.com/bkabrda))**

----------------------------------------

If I have e.g.

    make -C html

everything works fine, but when I have

    for <blabla...>
      make -C html
    done

the `make` is not matched, since it's indented by two spaces. This should be fixed in a way that transformers would accept arbitrary whitespace sequence at the start of the line.

----------------------------------------
- Bitbucket: https://bitbucket.org/bkabrda/spec2scl/issue/15

**Comment by irushchyshyn** [comment]
The transformers now accept arbitrary whitespace sequence at the start of the line.
Closing the issue. Please reopen if necessary.
