### ISSUE TITLE
Add set -ex

### ISSUE THREAD

**Issue by torsava** [sclorg/spec2scl#17]
Originally reported by: **Robert Kuska (Bitbucket: [xkuska](https://bitbucket.org/xkuska), GitHub: Unknown)**

----------------------------------------

More info https://github.com/fedora-python/python3/issues/2

----------------------------------------
- Bitbucket: https://bitbucket.org/bkabrda/spec2scl/issue/17

**Comment by irushchyshyn** [comment]
Whole commands are now wrapped in `scl enable` and are preceded with `set -e` according to [Packaging Guide](https://www.softwarecollections.org/en/docs/guide/#sect-Converting_RPM_Scripts).

Closing the issue. Please reopen if necessary.

**Comment by voxik** [comment]
Sorry, but this does not appear to be fixed:

https://github.com/sclorg/spec2scl/blob/master/spec2scl/settings.py#L18

There is just "set -e" which is not sufficient ...

**Comment by irushchyshyn** [comment]
Thanks for pointing this out! Fixed  in a96bd7e.
