### ISSUE TITLE
isatty check breaks scripts

### ISSUE THREAD

**Issue by msimacek** [sclorg/spec2scl#28]
`spec2scl -i foo.spec` works in a terminal, but not in a scripts:
````
spec2scl: error: You must either specify specfile(s) or reading from stdin, not both.
````

That's due to checking whether stdin is a tty. Please don't make assumptions about stdin and remove the check.

**Comment by irushchyshyn** [comment]
Hi @msimacek !
Thanks for reporting the issue.
The check was removed in within #30, could you please try it an let me know if it works for you?

**Comment by msimacek** [comment]
Seems to work now. Thanks!
