### ISSUE TITLE
Warning om tests usind python 3.6

### ISSUE THREAD

**Issue by tuxmaster5000** [sclorg/spec2scl#38]
Using python 3.6 to build it, will show some warnings at the test stage.:

> =============================== warnings summary ===============================
> /usr/lib/python3.6/site-packages/_pytest/mark/structures.py:337
>   /usr/lib/python3.6/site-packages/_pytest/mark/structures.py:337: PytestUnknownMarkWarning: Unknown pytest.mark.pep8 - is this a typo?  You can register custom marks to avoid this warning - for details, see htt
> ps://docs.pytest.org/en/latest/mark.html
>     PytestUnknownMarkWarning,
> 
> spec2scl/settings.py:24
> spec2scl/settings.py
>   /builddir/build/BUILD/spec2scl-1.2.1/spec2scl/settings.py:24: DeprecationWarning: invalid escape sequence \E
>     SCL_ENABLE = '%{?scl:scl enable %{scl} - << \EOF}\nset -ex\n'
> 
> tests/transformer_test_case.py:4
> tests/transformer_test_case.py
>   /builddir/build/BUILD/spec2scl-1.2.1/tests/transformer_test_case.py:4: DeprecationWarning: invalid escape sequence \E
>     scl_enable = '%{?scl:scl enable %{scl} - << \EOF}\nset -ex\n'
> 
> -- Docs: https://docs.pytest.org/en/latest/warnings.html
> ==================== 116 passed, 5 warnings in 0.95 seconds ====================

**Comment by khardix** [comment]
Thanks fo the report!

> invalid escape sequence \E

Should be fixed by 5ba9b50.

> Unknown pytest.mark.pep8

This is an [issue in pytest-pep8](https://bitbucket.org/pytest-dev/pytest-pep8/issues/23/pep8-mark-is-not-registered) which should have no impact on our code. b78aaca adds a warning filter to silence it.
